<?php
/**
 * Copyright © Acid Unit (https://acid.7prism.com). All rights reserved.
 * See LICENSE file for license details.
 */

/** @noinspection PhpUndefinedMethodInspection */

use AcidUnit\GoogleTagManager\ViewModel\ConfigProvider;
use Magento\Framework\View\Element\Template;
use Magento\Framework\View\Helper\SecureHtmlRenderer;

/**
 * @var ConfigProvider $configProvider
 * @var Template $block
 * @var SecureHtmlRenderer $secureRenderer
 */

$configProvider = $block->getConfigProvider(); // @phpstan-ignore-line
$containerId = $configProvider ? $configProvider->getContainerId() : ''; // @phpstan-ignore-line
$scriptString = <<<script
(function (w, d, s, l, i) {
        w[l] = w[l] || [];
        w[l].push({
            'gtm.start':
                new Date().getTime(), event: 'gtm.js'
        });
        var f = d.getElementsByTagName(s)[0],
            j = d.createElement(s), dl = l != 'dataLayer' ? '&l=' + l : '';
        j.async = true;
        j.src =
            'https://www.googletagmanager.com/gtm.js?id=' + i + dl;
        f.parentNode.insertBefore(j, f);
    })(window, document, 'script', 'dataLayer', '$containerId');
script;
?>

<?= /* @noEscape */ $secureRenderer->renderTag('script', [], $scriptString, false) ?>
