<?php
/**
 * Copyright © Acid Unit (https://acid.7prism.com). All rights reserved.
 * See LICENSE file for license details.
 */

/** @noinspection PhpUndefinedMethodInspection */

use AcidUnit\GoogleTagManager\Block\Base;
use AcidUnit\GoogleTagManager\Model\ProductDataUpdateHandler;
use Magento\Framework\Escaper;
use Magento\Framework\View\Helper\SecureHtmlRenderer;

/**
 * @var Base $block
 * @var ProductDataUpdateHandler $productDataUpdateHandler
 * @var Escaper $escaper
 * @var SecureHtmlRenderer $secureRenderer
 */

$productDataUpdateHandler = $block->getProductDataUpdateHandler(); // @phpstan-ignore-line
$scriptString = "window.acidProductData = {$productDataUpdateHandler->getPlaceholder()};";
?>

<?= /* @noEscape */ $secureRenderer->renderTag('script', [], $scriptString, false) ?>

<script type="text/x-magento-init">
{
    "*": {
        "AcidUnit_GoogleTagManager/js/init": {
            "pageHandle": "<?= /* @noEscape */ $escaper->escapeHtml($block->getPageHandle()) ?>",
            "pageData": <?= /* @escapeNotVerified */ $block->getSerializedPageData() ?>
        }
    }
}
</script>
