<?php
/**
 * Copyright © Acid Unit (https://acid.7prism.com). All rights reserved.
 * See LICENSE file for license details.
 */

/** @noinspection PhpUndefinedMethodInspection */

use AcidUnit\GoogleTagManager\ViewModel\ConfigProvider;
use Magento\Framework\View\Element\Template;
use Magento\Framework\View\Helper\SecureHtmlRenderer;

/**
 * @var ConfigProvider $configProvider
 * @var Template $block
 * @var SecureHtmlRenderer $secureRenderer
 */

$configProvider = $block->getConfigProvider(); // @phpstan-ignore-line
$containerId = $configProvider ? $configProvider->getContainerId() : ''; // @phpstan-ignore-line
$noscriptString = <<<noscript
<iframe src="https://www.googletagmanager.com/ns.html?id=$containerId"
        height="0" width="0" style="display:none;visibility:hidden"></iframe>
noscript;
?>

<?= /* @noEscape */ $secureRenderer->renderTag('noscript', [], $noscriptString, false) ?>
